In [1]:
# Testing numpy performance
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [5]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 35.9 ms


In [ ]:
# Never completed on my machine!
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

## The NumPy ndarray: A Multidimensional Array Object

In [1]:
import numpy as np

# generate some random data
data = np.random.randn(2, 3)

In [2]:
data

array([[ 0.39303409,  1.07443338,  1.26765111],
       [-1.3418576 ,  1.34997936, -0.4582348 ]])

In [3]:
# doing some math on this..
data * 2

array([[ 0.78606817,  2.14886675,  2.53530221],
       [-2.6837152 ,  2.69995872, -0.91646959]])

In [4]:
data * data

array([[0.15447579, 1.15440708, 1.60693933],
       [1.80058183, 1.82244427, 0.20997913]])

In [5]:
data + data

array([[ 0.78606817,  2.14886675,  2.53530221],
       [-2.6837152 ,  2.69995872, -0.91646959]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

### Creating ndarrays

In [8]:
data1 = [6, 7.5, 8, 0, -1]

In [11]:
# Creating an array
arr1 = np.array(data1)

In [12]:
arr1

array([ 6. ,  7.5,  8. ,  0. , -1. ])

In [22]:
# creating multi-dimensional arrays
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [23]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
# You cannot fool the system
data3 = [[1, 2, 3, 4], [5, 6, 7,]]
arr3 = np.array(data3)

c:\code\venv\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


In [25]:
# checking dimensions
arr2.ndim

2

In [26]:
# shape of the array
arr2.shape

(2, 4)

In [28]:
# as there are no floating points there.
arr2.dtype

dtype('int32')

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
# returning garbage values
np.empty((2, 3, 2))

array([[[8.27843524e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.01855798e-312, 2.67784513e+184]],

       [[3.14201913e+179, 2.87822983e+180],
        [1.42458121e+160, 1.83120903e-076],
        [6.86714330e+169, 2.62039873e+180]]])

In [34]:
#Built-in python range function.
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [35]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [36]:
arr1

array([1., 2., 3.])

In [38]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [39]:
arr2

array([1, 2, 3])

In [40]:
# You can explicitly convert or cast an array from one dtype to another using ndarray’s
# astype method:
arr = np.array([1, 2, 3, 4, 5])

In [42]:
arr.dtype

dtype('int32')

In [43]:
float_arr = arr.astype(np.float64)

In [44]:
float_arr

array([1., 2., 3., 4., 5.])

In [45]:
float_arr.dtype

dtype('float64')

In [46]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [47]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [48]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [49]:
numeric_strings = np.array(['1.23', '-2.45', '3.04'], dtype=np.string_)

In [50]:
numeric_strings.astype(float)

array([ 1.23, -2.45,  3.04])

In [51]:
# using other arrays datatype
int_array = np.arange(10)

In [52]:
calibers = np.array([.22, .270, .357], dtype=np.float64)

In [53]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [2]:
import numpy as np
empty_uint32 = np.empty(8, dtype='u4')

In [3]:
empty_uint32

array([1611466048,      32612,          0,          0,  942682933,
               52,          0,          0], dtype=uint32)

#### Arthmetic with NumPy Arrays

In [5]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [6]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [7]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [8]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [10]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [11]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [12]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [14]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [15]:
# Operations between equal size arrays is called vectorization.
# Operations between different sized arrays is called broadcasting.

#### Basic Indexing and Slicing

In [16]:
arr = np.arange(10)

In [17]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[5]

5

In [19]:
arr[5:8]

array([5, 6, 7])

In [20]:
arr[5:8] = 12

In [21]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [ ]:
# An important first distinction from Python’s built-in lists is that array slices are views on the original array. This means that the data is not copied, and any modifications to the view will be reflected in the source array.

In [22]:
arr_slice = arr[5:8]

In [23]:
arr_slice

array([12, 12, 12])

In [24]:
arr_slice[1] = 12345

In [25]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [26]:
arr_slice[:] = 64

In [27]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [29]:
# If you want to copy the part exclusively to different array
arr1 = np.arange(10)

In [30]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr1_slice_copy = arr1[5:8].copy()

In [32]:
arr1_slice_copy

array([5, 6, 7])

In [33]:
arr1_slice_copy[:] = 100

In [34]:
arr1_slice_copy

array([100, 100, 100])

In [36]:
arr1  # Notice they are unchanged.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# accessing elements in multidimentional arrays
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [39]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr2d[2]

array([7, 8, 9])

In [41]:
arr2d[0][2]

3

In [43]:
arr2d[0, 2]

3

In [44]:
# 3d arrays
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [45]:
arr3d  # this is 2 X 2 X 3 array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
arr3d[0]  # this is a 2 X 3 array

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
old_values = arr3d[0].copy()

In [48]:
arr3d[0] = 42

In [49]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
arr3d[0] = old_values

In [51]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [52]:
arr3d[1, 0]

array([7, 8, 9])

In [53]:
x = arr3d[1]

In [54]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [55]:
x[0]

array([7, 8, 9])

### Indexing with slices 

In [56]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [57]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [58]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [62]:
arr2d[1, :2]

array([4, 5])

In [63]:
arr2d[:2, 2]

array([3, 6])

In [64]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [67]:
arr2d[:2, 1:] = 0

In [68]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [69]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [70]:
data = np.random.randn(7, 4)

In [71]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [72]:
data

array([[ 0.84330888, -0.44061563,  0.06734361,  0.56247176],
       [-1.58986354, -0.77350595, -1.05387848, -0.49501235],
       [ 1.38667142, -1.72332726, -1.58758472, -1.32013522],
       [ 0.63380326,  0.60027404,  0.02297667, -0.34957928],
       [-0.45277875,  0.74108857, -0.32434373,  0.29127969],
       [-0.61646611,  1.91982876,  0.13072676,  0.92426205],
       [-0.44830041,  0.394489  ,  0.49097444, -0.9454369 ]])

In [74]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [75]:
data[names == 'Bob']  # bob occurs at place 0, 3. So the array is coming back from 0 and 3

array([[ 0.84330888, -0.44061563,  0.06734361,  0.56247176],
       [ 0.63380326,  0.60027404,  0.02297667, -0.34957928]])

In [77]:
data[names == 'Bob', 2:]

array([[ 0.06734361,  0.56247176],
       [ 0.02297667, -0.34957928]])

In [78]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [79]:
data[names != 'Bob']

array([[-1.58986354, -0.77350595, -1.05387848, -0.49501235],
       [ 1.38667142, -1.72332726, -1.58758472, -1.32013522],
       [-0.45277875,  0.74108857, -0.32434373,  0.29127969],
       [-0.61646611,  1.91982876,  0.13072676,  0.92426205],
       [-0.44830041,  0.394489  ,  0.49097444, -0.9454369 ]])

In [80]:
data[~(names == 'Bob')]  # same as above.

array([[-1.58986354, -0.77350595, -1.05387848, -0.49501235],
       [ 1.38667142, -1.72332726, -1.58758472, -1.32013522],
       [-0.45277875,  0.74108857, -0.32434373,  0.29127969],
       [-0.61646611,  1.91982876,  0.13072676,  0.92426205],
       [-0.44830041,  0.394489  ,  0.49097444, -0.9454369 ]])

In [81]:
# ~ can used to invert the condition.
cond = names == 'Bob'

In [82]:
data[~cond]

array([[-1.58986354, -0.77350595, -1.05387848, -0.49501235],
       [ 1.38667142, -1.72332726, -1.58758472, -1.32013522],
       [-0.45277875,  0.74108857, -0.32434373,  0.29127969],
       [-0.61646611,  1.91982876,  0.13072676,  0.92426205],
       [-0.44830041,  0.394489  ,  0.49097444, -0.9454369 ]])

In [83]:
# multi selection
mask = (names == 'Bob') | (names == 'Will')
# python keywords and, or doesn't work with boolean arraya
# instead use & , | for and, or operations respectively.

In [84]:
mask

array([ True, False,  True,  True,  True, False, False])

In [85]:
data[mask]

array([[ 0.84330888, -0.44061563,  0.06734361,  0.56247176],
       [ 1.38667142, -1.72332726, -1.58758472, -1.32013522],
       [ 0.63380326,  0.60027404,  0.02297667, -0.34957928],
       [-0.45277875,  0.74108857, -0.32434373,  0.29127969]])

In [86]:
# marking all values as 0 which are negative
data

array([[ 0.84330888, -0.44061563,  0.06734361,  0.56247176],
       [-1.58986354, -0.77350595, -1.05387848, -0.49501235],
       [ 1.38667142, -1.72332726, -1.58758472, -1.32013522],
       [ 0.63380326,  0.60027404,  0.02297667, -0.34957928],
       [-0.45277875,  0.74108857, -0.32434373,  0.29127969],
       [-0.61646611,  1.91982876,  0.13072676,  0.92426205],
       [-0.44830041,  0.394489  ,  0.49097444, -0.9454369 ]])

In [87]:
data[data < 0]

array([-0.44061563, -1.58986354, -0.77350595, -1.05387848, -0.49501235,
       -1.72332726, -1.58758472, -1.32013522, -0.34957928, -0.45277875,
       -0.32434373, -0.61646611, -0.44830041, -0.9454369 ])

In [88]:
data[data < 0] = 0

In [89]:
data

array([[0.84330888, 0.        , 0.06734361, 0.56247176],
       [0.        , 0.        , 0.        , 0.        ],
       [1.38667142, 0.        , 0.        , 0.        ],
       [0.63380326, 0.60027404, 0.02297667, 0.        ],
       [0.        , 0.74108857, 0.        , 0.29127969],
       [0.        , 1.91982876, 0.13072676, 0.92426205],
       [0.        , 0.394489  , 0.49097444, 0.        ]])

In [90]:
# setting whole rows or columns using a one dimensional boolean array is also easy
data

array([[0.84330888, 0.        , 0.06734361, 0.56247176],
       [0.        , 0.        , 0.        , 0.        ],
       [1.38667142, 0.        , 0.        , 0.        ],
       [0.63380326, 0.60027404, 0.02297667, 0.        ],
       [0.        , 0.74108857, 0.        , 0.29127969],
       [0.        , 1.91982876, 0.13072676, 0.92426205],
       [0.        , 0.394489  , 0.49097444, 0.        ]])

In [92]:
data[names != 'Joe'] = 7

In [93]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.91982876, 0.13072676, 0.92426205],
       [0.        , 0.394489  , 0.49097444, 0.        ]])

### Fancy Indexing

In [94]:
# indexing using integer arrays

In [95]:
arr = np.empty((8, 4))

In [97]:
for i in range(8): arr[i] = i

In [98]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [99]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [100]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [101]:
arr = np.arange(32).reshape((8, 4))

In [102]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [103]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]  # we should see like (1, 0), (5, 3) etc.

array([ 4, 23, 29, 10])

In [104]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Transposing Arrays and Swapping Axes

In [105]:
arr = np.arange(15).reshape((3, 5))

In [106]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [108]:
arr.T  # transposing

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [109]:
arr = np.random.randn(6, 3)

In [110]:
arr

array([[-0.73155009, -0.21758604, -0.39941649],
       [-0.68865927,  0.38724525,  0.24137447],
       [-0.74422197, -1.11179142,  1.00712533],
       [ 1.24990797, -0.21793049, -0.8567101 ],
       [ 0.8721134 ,  1.43489699,  0.93463471],
       [ 1.2036543 , -1.19183166,  0.16775463]])

In [111]:
np.dot(arr.T, arr)

array([[ 5.33491885,  0.26436118, -0.67733913],
       [ 0.26436118,  4.9602685 ,  0.38853777],
       [-0.67733913,  0.38853777,  2.86773245]])

In [112]:
# somewhat extra mind bending
arr = np.arange(16).reshape((2, 2, 4))

In [113]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [114]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [115]:
# swapping axes
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [116]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])