In [1]:
# Testing numpy performance
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [5]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 35.9 ms


In [ ]:
# Never completed on my machine!
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

## The NumPy ndarray: A Multidimensional Array Object

In [1]:
import numpy as np

# generate some random data
data = np.random.randn(2, 3)

In [2]:
data

array([[ 0.39303409,  1.07443338,  1.26765111],
       [-1.3418576 ,  1.34997936, -0.4582348 ]])

In [3]:
# doing some math on this..
data * 2

array([[ 0.78606817,  2.14886675,  2.53530221],
       [-2.6837152 ,  2.69995872, -0.91646959]])

In [4]:
data * data

array([[0.15447579, 1.15440708, 1.60693933],
       [1.80058183, 1.82244427, 0.20997913]])

In [5]:
data + data

array([[ 0.78606817,  2.14886675,  2.53530221],
       [-2.6837152 ,  2.69995872, -0.91646959]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

### Creating ndarrays

In [8]:
data1 = [6, 7.5, 8, 0, -1]

In [11]:
# Creating an array
arr1 = np.array(data1)

In [12]:
arr1

array([ 6. ,  7.5,  8. ,  0. , -1. ])

In [22]:
# creating multi-dimensional arrays
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [23]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
# You cannot fool the system
data3 = [[1, 2, 3, 4], [5, 6, 7,]]
arr3 = np.array(data3)

c:\code\venv\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


In [25]:
# checking dimensions
arr2.ndim

2

In [26]:
# shape of the array
arr2.shape

(2, 4)

In [28]:
# as there are no floating points there.
arr2.dtype

dtype('int32')

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
# returning garbage values
np.empty((2, 3, 2))

array([[[8.27843524e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.01855798e-312, 2.67784513e+184]],

       [[3.14201913e+179, 2.87822983e+180],
        [1.42458121e+160, 1.83120903e-076],
        [6.86714330e+169, 2.62039873e+180]]])

In [34]:
#Built-in python range function.
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [35]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [36]:
arr1

array([1., 2., 3.])

In [38]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [39]:
arr2

array([1, 2, 3])

In [40]:
# You can explicitly convert or cast an array from one dtype to another using ndarray’s
# astype method:
arr = np.array([1, 2, 3, 4, 5])

In [42]:
arr.dtype

dtype('int32')

In [43]:
float_arr = arr.astype(np.float64)

In [44]:
float_arr

array([1., 2., 3., 4., 5.])

In [45]:
float_arr.dtype

dtype('float64')

In [46]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [47]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [48]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [49]:
numeric_strings = np.array(['1.23', '-2.45', '3.04'], dtype=np.string_)

In [50]:
numeric_strings.astype(float)

array([ 1.23, -2.45,  3.04])

In [51]:
# using other arrays datatype
int_array = np.arange(10)

In [52]:
calibers = np.array([.22, .270, .357], dtype=np.float64)

In [53]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])