In [1]:
import numpy as np
import math

In [2]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [3]:
print(a.ndim)

1


In [4]:
b = np.array([[1, 2,3 ], [4, 5, 6]])

In [5]:
b.shape

(2, 3)

In [6]:
a.dtype

dtype('int64')

In [7]:
c = np.array([2.2, 5, 1.1])

In [11]:
c.dtype.name

'float64'

In [12]:
d = np.zeros((2, 3))

In [13]:
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.arange(10, 50, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [18]:
np.linspace(0, 2, 15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [20]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

In [21]:
c = a - b
c

array([ 9, 18, 27, 36])

In [24]:
d = a * b
d

array([ 10,  40,  90, 160])

In [25]:
f = np.array([0, -10, -5, -8])
c = f - 31 * 5 / 9

In [26]:
c

array([-17.22222222, -27.22222222, -22.22222222, -25.22222222])

In [27]:
# creating data sets of defined shapes
b = np.arange(1, 101, 1).reshape(10, 10)

In [28]:
b

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [29]:
b[8, 9]  # row, column

90

In [30]:
np.array([b[8, 9], b[2, 7]])

array([90, 28])

In [32]:
# zipping the lists
print(b[[0, 6, 8], [3, 5, 6]])

[ 4 66 87]


In [33]:
np.array(b[[0, 6, 8], [3, 5, 6]])

array([ 4, 66, 87])

In [34]:
print(b > 10)

[[False False False False False False False False False False]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


In [37]:
print(b[b > 5])

[  6   7   8   9  10  11  12  13  14  15  16  17  18  19  20  21  22  23
  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41
  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59
  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95
  96  97  98  99 100]


In [38]:
np.array(b[b > 5])

array([  6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,
        19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,
        32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,
        45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
        58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
        71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
        84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,
        97,  98,  99, 100])

In [39]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [40]:
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
b = np.arange(1, 51).reshape(10, 5)
c = np.arange(51, 101).reshape(10, 5)
print(b)
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
[[ 51  52  53  54  55]
 [ 56  57  58  59  60]
 [ 61  62  63  64  65]
 [ 66  67  68  69  70]
 [ 71  72  73  74  75]
 [ 76  77  78  79  80]
 [ 81  82  83  84  85]
 [ 86  87  88  89  90]
 [ 91  92  93  94  95]
 [ 96  97  98  99 100]]


In [50]:
d = np.array([b, c])
e = np.array([[np.arange(1, 51).reshape(10, 5)], [np.arange(51, 101).reshape(10, 5)]])

In [46]:
d

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25],
        [ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75],
        [ 76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]]])

In [51]:
e

array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20],
         [ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40],
         [ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50]]],


       [[[ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60],
         [ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80],
         [ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]]]])

In [52]:
e.shape

(2, 1, 10, 5)

In [53]:
e.size

100

In [54]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [55]:
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
a[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [59]:
a[1, 1:3]

array([6, 7])

In [60]:
sub_array = a[:2, 1:3]

In [61]:
sub_array

array([[2, 3],
       [6, 7]])

In [62]:
sub_array[0, 0] = 50

In [63]:
sub_array

array([[50,  3],
       [ 6,  7]])

In [64]:
a

array([[ 1, 50,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### using datasets

In [67]:
wines = np.genfromtxt('winequality-red.csv', delimiter=';', skip_header=1)

In [68]:
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [69]:
wines[:, 0]

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

In [70]:
wines[:, 0:1]

array([[7.4],
       [7.8],
       [7.8],
       ...,
       [6.3],
       [5.9],
       [6. ]])

In [72]:
wines[:, 0:1][1]

array([7.8])

In [73]:
wines[:, 0][1]

7.8

In [74]:
wines[:, 0:3]

array([[7.4  , 0.7  , 0.   ],
       [7.8  , 0.88 , 0.   ],
       [7.8  , 0.76 , 0.04 ],
       ...,
       [6.3  , 0.51 , 0.13 ],
       [5.9  , 0.645, 0.12 ],
       [6.   , 0.31 , 0.47 ]])

In [77]:
wines[:, [0, 2, 4]]

array([[7.4  , 0.   , 0.076],
       [7.8  , 0.   , 0.098],
       [7.8  , 0.04 , 0.092],
       ...,
       [6.3  , 0.13 , 0.076],
       [5.9  , 0.12 , 0.075],
       [6.   , 0.47 , 0.067]])

In [81]:
wines[:, [0, 2, 4]][2, :]

array([7.8  , 0.04 , 0.092])

In [82]:
wines[:, -1].mean()

5.6360225140712945

### one more dataset graduate admissions

In [91]:
graduate_admission = np.genfromtxt('Admission_Predict.csv', dtype=None, delimiter=',', skip_header=1,
                                   names=('Serial No','GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
                                          'LOR','CGPA','Research', 'Chance of Admit'))

In [92]:
graduate_admission

array([(  1, 337, 118, 4, 4.5, 4.5, 9.65, 1, 0.92),
       (  2, 324, 107, 4, 4. , 4.5, 8.87, 1, 0.76),
       (  3, 316, 104, 3, 3. , 3.5, 8.  , 1, 0.72),
       (  4, 322, 110, 3, 3.5, 2.5, 8.67, 1, 0.8 ),
       (  5, 314, 103, 2, 2. , 3. , 8.21, 0, 0.65),
       (  6, 330, 115, 5, 4.5, 3. , 9.34, 1, 0.9 ),
       (  7, 321, 109, 3, 3. , 4. , 8.2 , 1, 0.75),
       (  8, 308, 101, 2, 3. , 4. , 7.9 , 0, 0.68),
       (  9, 302, 102, 1, 2. , 1.5, 8.  , 0, 0.5 ),
       ( 10, 323, 108, 3, 3.5, 3. , 8.6 , 0, 0.45),
       ( 11, 325, 106, 3, 3.5, 4. , 8.4 , 1, 0.52),
       ( 12, 327, 111, 4, 4. , 4.5, 9.  , 1, 0.84),
       ( 13, 328, 112, 4, 4. , 4.5, 9.1 , 1, 0.78),
       ( 14, 307, 109, 3, 4. , 3. , 8.  , 1, 0.62),
       ( 15, 311, 104, 3, 3.5, 2. , 8.2 , 1, 0.61),
       ( 16, 314, 105, 3, 3.5, 2.5, 8.3 , 0, 0.54),
       ( 17, 317, 107, 3, 4. , 3. , 8.7 , 0, 0.66),
       ( 18, 319, 106, 3, 4. , 3. , 8.  , 1, 0.65),
       ( 19, 318, 110, 3, 4. , 3. , 8.8 , 0, 0.63),
       ( 20,

In [95]:
graduate_admission = np.genfromtxt('Admission_Predict.csv',delimiter=',', skip_header=1,)

In [96]:
graduate_admission

array([[  1.  , 337.  , 118.  , ...,   9.65,   1.  ,   0.92],
       [  2.  , 324.  , 107.  , ...,   8.87,   1.  ,   0.76],
       [  3.  , 316.  , 104.  , ...,   8.  ,   1.  ,   0.72],
       ...,
       [398.  , 330.  , 116.  , ...,   9.45,   1.  ,   0.91],
       [399.  , 312.  , 103.  , ...,   8.78,   0.  ,   0.67],
       [400.  , 333.  , 117.  , ...,   9.66,   1.  ,   0.95]])

In [97]:
graduate_admission = np.genfromtxt('Admission_Predict.csv', dtype=None, delimiter=',', skip_header=1,
                                   names=('Serial No','GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
                                          'LOR','CGPA','Research', 'Chance of Admit'))

In [98]:
graduate_admission

array([(  1, 337, 118, 4, 4.5, 4.5, 9.65, 1, 0.92),
       (  2, 324, 107, 4, 4. , 4.5, 8.87, 1, 0.76),
       (  3, 316, 104, 3, 3. , 3.5, 8.  , 1, 0.72),
       (  4, 322, 110, 3, 3.5, 2.5, 8.67, 1, 0.8 ),
       (  5, 314, 103, 2, 2. , 3. , 8.21, 0, 0.65),
       (  6, 330, 115, 5, 4.5, 3. , 9.34, 1, 0.9 ),
       (  7, 321, 109, 3, 3. , 4. , 8.2 , 1, 0.75),
       (  8, 308, 101, 2, 3. , 4. , 7.9 , 0, 0.68),
       (  9, 302, 102, 1, 2. , 1.5, 8.  , 0, 0.5 ),
       ( 10, 323, 108, 3, 3.5, 3. , 8.6 , 0, 0.45),
       ( 11, 325, 106, 3, 3.5, 4. , 8.4 , 1, 0.52),
       ( 12, 327, 111, 4, 4. , 4.5, 9.  , 1, 0.84),
       ( 13, 328, 112, 4, 4. , 4.5, 9.1 , 1, 0.78),
       ( 14, 307, 109, 3, 4. , 3. , 8.  , 1, 0.62),
       ( 15, 311, 104, 3, 3.5, 2. , 8.2 , 1, 0.61),
       ( 16, 314, 105, 3, 3.5, 2.5, 8.3 , 0, 0.54),
       ( 17, 317, 107, 3, 4. , 3. , 8.7 , 0, 0.66),
       ( 18, 319, 106, 3, 4. , 3. , 8.  , 1, 0.65),
       ( 19, 318, 110, 3, 4. , 3. , 8.8 , 0, 0.63),
       ( 20,

In [100]:
graduate_admission['CGPA'][0:5]

array([9.65, 8.87, 8.  , 8.67, 8.21])

In [101]:
graduate_admission['CGPA'] = graduate_admission['CGPA'] / 10 + 4

In [103]:
graduate_admission['CGPA'][0:5]

array([4.965, 4.887, 4.8  , 4.867, 4.821])

In [104]:
# boolean masking
len(graduate_admission[graduate_admission['Research'] == 1])

219

In [105]:
print(graduate_admission[graduate_admission['Chance_of_Admit'] > 0.8]['GRE_Score'].mean())
print(graduate_admission[graduate_admission['Chance_of_Admit'] < 0.4]['GRE_Score'].mean())

328.7350427350427
302.2857142857143


In [112]:
graduate_admission[graduate_admission['Chance_of_Admit'] > 0.8]

array([(  1, 337, 118, 4, 4.5, 4.5, 4.965, 1, 0.92),
       (  6, 330, 115, 5, 4.5, 3. , 4.934, 1, 0.9 ),
       ( 12, 327, 111, 4, 4. , 4.5, 4.9  , 1, 0.84),
       ( 23, 328, 116, 5, 5. , 5. , 4.95 , 1, 0.94),
       ( 24, 334, 119, 5, 5. , 4.5, 4.97 , 1, 0.95),
       ( 25, 336, 119, 5, 4. , 3.5, 4.98 , 1, 0.97),
       ( 26, 340, 120, 5, 4.5, 4.5, 4.96 , 1, 0.94),
       ( 33, 338, 118, 4, 3. , 4.5, 4.94 , 1, 0.91),
       ( 34, 340, 114, 5, 4. , 4. , 4.96 , 1, 0.9 ),
       ( 35, 331, 112, 5, 4. , 5. , 4.98 , 1, 0.94),
       ( 36, 320, 110, 5, 5. , 5. , 4.92 , 1, 0.88),
       ( 44, 332, 117, 4, 4.5, 4. , 4.91 , 0, 0.87),
       ( 45, 326, 113, 5, 4.5, 4. , 4.94 , 1, 0.91),
       ( 46, 322, 110, 5, 5. , 4. , 4.91 , 1, 0.88),
       ( 47, 329, 114, 5, 4. , 5. , 4.93 , 1, 0.86),
       ( 48, 339, 119, 5, 4.5, 4. , 4.97 , 0, 0.89),
       ( 49, 321, 110, 3, 3.5, 5. , 4.885, 1, 0.82),
       ( 71, 332, 118, 5, 5. , 5. , 4.964, 1, 0.94),
       ( 72, 336, 112, 5, 5. , 5. , 4.976, 1, 

In [113]:
graduate_admission[graduate_admission['Chance_of_Admit'] > 0.8]['GRE_Score']

array([337, 330, 327, 328, 334, 336, 340, 338, 340, 331, 320, 332, 326,
       322, 329, 339, 321, 332, 336, 321, 314, 340, 320, 322, 340, 331,
       332, 329, 338, 331, 335, 334, 323, 326, 333, 339, 333, 314, 329,
       332, 331, 340, 320, 326, 339, 334, 332, 321, 329, 334, 322, 323,
       321, 320, 329, 319, 327, 317, 335, 331, 324, 324, 323, 322, 336,
       340, 334, 328, 338, 333, 331, 330, 322, 321, 324, 324, 330, 326,
       325, 329, 328, 335, 321, 331, 327, 327, 329, 312, 340, 331, 336,
       324, 314, 320, 330, 328, 326, 325, 332, 323, 324, 321, 322, 334,
       338, 330, 324, 336, 324, 340, 335, 326, 329, 324, 325, 330, 333])

In [114]:
graduate_admission[graduate_admission['Chance_of_Admit'] > 0.8]['GRE_Score'].mean()

328.7350427350427

In [115]:
graduate_admission[graduate_admission['Chance_of_Admit'] > 0.8]['CGPA'].mean()

4.927666666666667

In [116]:
graduate_admission[graduate_admission['Chance_of_Admit'] < 0.4]['CGPA'].mean()

4.755571428571429