In [1]:
import numpy as np

In [4]:
data = np.random.randn(2, 3)
data

array([[ 0.23953475, -2.24964278, -0.759576  ],
       [-1.2737969 , -0.195009  ,  0.31434022]])

In [5]:
data * 2

array([[ 0.4790695 , -4.49928555, -1.51915201],
       [-2.5475938 , -0.39001801,  0.62868045]])

In [7]:
data1 = np.random.randn(2, 3)
data2 = np.random.randn(3, 2)
data1 @ data2

array([[-0.00998787,  1.04759069],
       [ 0.32704741,  0.57743184]])

In [16]:
# declaring 2 arrays and multiplying.
data1 = np.array([[1, 2, 3], [4, 5, 6]])
data2 = np.array([[3, 2,], [6, 5,], [2, 4]])

In [17]:
data1

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
data2

array([[3, 2],
       [6, 5],
       [2, 4]])

In [19]:
data1.shape

(2, 3)

In [20]:
data1 * data2

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [21]:
data1 @ data2

array([[21, 24],
       [54, 57]])

In [22]:
np.ndim(data1 @ data2)

2

In [23]:
data1.dtype

dtype('int64')

In [24]:
data2.dtype

dtype('int64')

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [39]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
arr = np.arange(10)

In [41]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr[5]

5

In [50]:
arr[5:8]

array([12, 12, 12])

In [51]:
arr[5:8] = 12

In [52]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [53]:
arr_slice = arr[5:8]

In [54]:
arr_slice

array([12, 12, 12])

In [55]:
arr_slice[:]=0

In [56]:
arr

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

In [82]:
board = np.arange(1,91).reshape(9, 10)

In [83]:
board

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [67]:
board

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [72]:
board[2]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [75]:
arr2d = ([[np.arange(10)], [np.arange(10,20)], [np.arange(20,30)]])

In [76]:
arr2d

[[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])],
 [array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])],
 [array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])]]