In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 12.3 ms, sys: 161 µs, total: 12.5 ms
Wall time: 12.7 ms


In [5]:
%time for _ in range(10): my_list = [x * 2 for x in my_list]

CPU times: user 227 ms, sys: 83.3 ms, total: 310 ms
Wall time: 309 ms


## The NumPy ndarray: A multidimentional Array Object

In [33]:
import numpy as np

In [34]:
data = np.random.randn(2, 3)

In [35]:
data

array([[ 1.75652294,  0.29932982,  0.33359787],
       [ 1.4322791 , -0.96795393,  0.27462124]])

In [36]:
data * 2

array([[ 3.51304587,  0.59865964,  0.66719573],
       [ 2.86455821, -1.93590785,  0.54924248]])

In [37]:
data + data

array([[ 3.51304587,  0.59865964,  0.66719573],
       [ 2.86455821, -1.93590785,  0.54924248]])

In [38]:
data * 6

array([[10.53913762,  1.79597893,  2.0015872 ],
       [ 8.59367462, -5.80772356,  1.64772744]])

In [39]:
data = data * 6

In [40]:
data

array([[10.53913762,  1.79597893,  2.0015872 ],
       [ 8.59367462, -5.80772356,  1.64772744]])

In [41]:
data.dtype

dtype('float64')

In [42]:
data.size

6

In [43]:
data.shape

(2, 3)

In [44]:
data = data.transpose()

In [46]:
data.shape

(3, 2)

In [61]:
t_board = np.arange(1, 91)

In [58]:
t_board

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90])

In [65]:
data1 = [6, 7.5, 8, 0, 1]

In [66]:
arr1 = np.array(data1)

In [67]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [73]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [74]:
arr2 = np.array(data2)

In [75]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [72]:
[i for i in range(1, 11)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [76]:
arr2.ndim

2

In [77]:
arr2.shape

(2, 4)

In [78]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [79]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [81]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [82]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [83]:
ones = np.ones((2, 2))
zeros = np.zeros((2, 2))

In [84]:
print(ones)
print(zeros)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


In [87]:
sums = ones + zeros + ones

In [88]:
sums

array([[2., 2.],
       [2., 2.]])

In [89]:
np.empty((2, 3, 2))

array([[[4.65705064e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [90]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [96]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [99]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [100]:
arr1

array([1., 2., 3.])

In [101]:
arr1.dtype

dtype('float64')

In [105]:
arr2 = np.array([1., 2., 3.], dtype=np.int32)

In [106]:
arr2

array([1, 2, 3], dtype=int32)

In [107]:
arr = np.array([1, 2, 3, 4, 5])

In [108]:
arr.dtype

dtype('int64')

In [109]:
arr.astype(np.float64)

array([1., 2., 3., 4., 5.])

In [110]:
arr = np.array([1.3, -3.5, -8, 0.5])

In [111]:
arr.astype(np.int32)

array([ 1, -3, -8,  0], dtype=int32)

In [112]:
s1 = ['1', '2', '3', '4']

In [113]:
np.array(s1)

array(['1', '2', '3', '4'], dtype='<U1')

In [115]:
np.array(s1, dtype=np.int32)

array([1, 2, 3, 4], dtype=int32)

In [116]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [122]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [123]:
calibers.astype(int_array.dtype)

array([0, 0, 0, 0, 0, 0])

### Basic Indexing and Slicing

In [124]:
arr = np.arange(10)

In [125]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
arr[5]

5

In [127]:
arr[5:8]

array([5, 6, 7])

In [128]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [129]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [130]:
arr_slice = arr[5:8]

In [131]:
arr_slice

array([12, 12, 12])

In [132]:
arr_slice[1] = 12345
arr_slice

array([   12, 12345,    12])

In [133]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [134]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

##### 2D arrays

In [138]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [139]:
arr2d[0][2]

3

In [140]:
arr2d[0]

array([1, 2, 3])

In [141]:
arr2d[2]

array([7, 8, 9])

In [142]:
arr2d[0, 2]

3

In [144]:
arr2d[0, 2]

3

In [145]:
arr2d.size

9

In [146]:
arr2d.shape

(3, 3)

In [148]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [152]:
arr3d[1, 0]

array([7, 8, 9])