In [1]:
# The NumPy ndarray: A multidimensional Array Object
import numpy as np
data = np.random.randn(2, 3)
data

array([[-0.15698896, -0.735315  ,  1.00873367],
       [-0.15236497,  0.94580369,  0.14795986]])

In [2]:
data * 10

array([[-1.56988959, -7.35315004, 10.08733666],
       [-1.52364969,  9.4580369 ,  1.47959855]])

In [3]:
data + data

array([[-0.31397792, -1.47063001,  2.01746733],
       [-0.30472994,  1.89160738,  0.29591971]])

In [4]:
data.shape

(2, 3)

In [5]:
data.dtype

dtype('float64')

In [8]:
# Creating ndarrays
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.ndim

2

In [11]:
arr1.ndim

1

In [12]:
arr2.shape

(2, 4)

In [13]:
arr1.dtype

dtype('float64')

In [14]:
arr2.dtype

dtype('int64')

In [15]:
# Some buildin functions to create data.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [25]:
# built in range
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
# Data Types for ndarrays
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [27]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [29]:
arr3 = np.array([1., 2., 3.,], dtype=np.int32) # converting datatype
arr3

array([1, 2, 3], dtype=int32)

In [30]:
# array type conversion
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [31]:
float_arr = arr.astype(np.float64)

In [32]:
float_arr

array([1., 2., 3., 4., 5.])

In [33]:
arr = np.array([5.7, 3.6, -0.4, 1.0, 5.97])
arr.dtype

dtype('float64')

In [34]:
arr.astype(np.int32)

array([5, 3, 0, 1, 5], dtype=int32)

In [35]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [36]:
# casting the datatype of one array to another
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [37]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [38]:
# Arthmetic with NumPy Arrays
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [39]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [40]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [42]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [43]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [44]:
arr2 > arr1

array([[False,  True, False],
       [ True, False,  True]])

In [45]:
# Basic Indexing and Slicing
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr[5]

5

In [47]:
arr[5:8]

array([5, 6, 7])

In [48]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [49]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [50]:
arr_slice[1] = 12345

In [51]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [52]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [53]:
# testing .copy()
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr_slice = arr[5:8].copy()
arr_slice

array([5, 6, 7])

In [56]:
arr_slice

array([5, 6, 7])

In [57]:
arr_slice[:] = 123
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
# Slicing on 2d arrays
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [60]:
arr2d[0][2]

3

In [61]:
arr2d[0, 2]  # Equivalent

3

In [75]:
# Slicing a 3d array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [76]:
arr3d[0][0][2]

3

In [77]:
arr3d[0, 0, 2]

3

In [78]:
old_values = arr3d[0].copy()

In [79]:
arr3d[0] = 123

In [80]:
arr3d

array([[[123, 123, 123],
        [123, 123, 123]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [81]:
arr3d[0] = old_values

In [82]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [83]:
# Indexing with slices
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [85]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [88]:
arr2d[1, :2]

array([4, 5])

In [89]:
arr2d[:2, 2]

array([3, 6])

In [94]:
# : means you can take entire axis.
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [95]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [96]:
# Boolean Indexing
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [97]:
data = np.random.randn(7, 4)

In [98]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [99]:
data

array([[-1.23735982, -0.52781123,  2.11531321,  1.16896181],
       [-0.23392053, -1.80448149, -0.96571427,  0.89598172],
       [-0.09178738,  0.8653665 , -1.00859788, -0.3111775 ],
       [ 0.07237789, -0.3130914 , -0.24848596,  1.43864909],
       [ 0.91157235,  0.99530393,  1.30361094,  1.24197071],
       [-0.24320402,  1.26425766, -1.08316423,  1.87410951],
       [ 0.93039007, -0.86540514,  0.1415633 , -0.89039341]])

In [100]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [101]:
data[names == 'Bob']  # On axis 0, row 0 and 3 got selected.

array([[-1.23735982, -0.52781123,  2.11531321,  1.16896181],
       [ 0.07237789, -0.3130914 , -0.24848596,  1.43864909]])

In [102]:
data[names == 'Bob', 2:]

array([[ 2.11531321,  1.16896181],
       [-0.24848596,  1.43864909]])

In [103]:
data[names == 'Bob', 3]

array([1.16896181, 1.43864909])

In [104]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [105]:
data[~(names == 'Bob')]

array([[-0.23392053, -1.80448149, -0.96571427,  0.89598172],
       [-0.09178738,  0.8653665 , -1.00859788, -0.3111775 ],
       [ 0.91157235,  0.99530393,  1.30361094,  1.24197071],
       [-0.24320402,  1.26425766, -1.08316423,  1.87410951],
       [ 0.93039007, -0.86540514,  0.1415633 , -0.89039341]])

In [107]:
# Inverting a general condition
cond = names == 'Bob'
data[~cond]

array([[-0.23392053, -1.80448149, -0.96571427,  0.89598172],
       [-0.09178738,  0.8653665 , -1.00859788, -0.3111775 ],
       [ 0.91157235,  0.99530393,  1.30361094,  1.24197071],
       [-0.24320402,  1.26425766, -1.08316423,  1.87410951],
       [ 0.93039007, -0.86540514,  0.1415633 , -0.89039341]])

In [108]:
# multiple selections for boolean masks
mask = (names == 'Bob') | (names == 'Will')

In [109]:
mask

array([ True, False,  True,  True,  True, False, False])

In [110]:
data[mask]

array([[-1.23735982, -0.52781123,  2.11531321,  1.16896181],
       [-0.09178738,  0.8653665 , -1.00859788, -0.3111775 ],
       [ 0.07237789, -0.3130914 , -0.24848596,  1.43864909],
       [ 0.91157235,  0.99530393,  1.30361094,  1.24197071]])

In [111]:
# boolean masking in common sense way
data[data < 0] = 0
data

array([[0.        , 0.        , 2.11531321, 1.16896181],
       [0.        , 0.        , 0.        , 0.89598172],
       [0.        , 0.8653665 , 0.        , 0.        ],
       [0.07237789, 0.        , 0.        , 1.43864909],
       [0.91157235, 0.99530393, 1.30361094, 1.24197071],
       [0.        , 1.26425766, 0.        , 1.87410951],
       [0.93039007, 0.        , 0.1415633 , 0.        ]])

In [112]:
data[names != 'Joe'] = 7  # Impacting all rows.
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.89598172],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.26425766, 0.        , 1.87410951],
       [0.93039007, 0.        , 0.1415633 , 0.        ]])

In [115]:
# Fancy Indexing
arr = np.empty((8, 4))  # axis 0:8, axis 1:4

In [116]:
arr[0]

array([0., 0., 0., 0.])

In [117]:
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [118]:
# subset selection.
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [119]:
arr[4, 3, 0, 6]  # This error is expected if not passed as a subset.

IndexError: too many indices for array: array is 2-dimensional, but 4 were indexed

In [120]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [125]:
# reshaping ranges
arr = np.arange(32).reshape(8, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [126]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]  # effectively selecting (1, 0), (5, 3) etc.

array([ 4, 23, 29, 10])

In [127]:
# one more way of fancy indexing.
arr[[1, 5, 7, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [128]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [129]:
# Transposing Arrays and Swapping Axes
arr = np.arange(15).reshape(3, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [130]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [131]:
arr = np.random.randn(6, 3)

In [132]:
arr

array([[-0.64525606, -1.82278489, -0.21828443],
       [-1.44713791, -1.2529503 ,  0.85338868],
       [-2.60226793, -0.481783  ,  0.04017452],
       [-1.66418863,  0.95770853,  0.86788273],
       [-0.45426909, -0.64134282, -0.16001296],
       [ 0.10510968,  0.59669015, -0.11323977]])

In [133]:
np.dot(arr.T, arr)  # inner matrix product

array([[12.26929412,  3.0033358 , -2.58220086],
       [ 3.0033358 ,  6.80910943,  0.17550934],
       [-2.58220086,  0.17550934,  1.56918215]])

In [134]:
arr = np.arange(16).reshape(2, 2, 4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [135]:
arr.transpose(1, 0, 2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [136]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [137]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])