In [1]:
# 0d array
import numpy as np
a = 1
A = np.array(a)
print(A)
print(A.size)
print(A.shape)
print(A.ndim)

1
1
()
0


In [2]:
# 1d array
# [list]
b = [1,]
B = np.array(b)
print(B)
print(B.size)
print(B.shape)
print(B.ndim)

[1]
1
(1,)
1


In [3]:
# 1d array can be of multiple values in a list.
# [list]
b = [1, 2, 3, 4]
B = np.array(b)
print(B)
print(B.size)
print(B.shape)
print(B.ndim)

[1 2 3 4]
4
(4,)
1


In [4]:
# 2d array
[[list], [list]]
c = [[1, 2, 3, 4], [5, 6, 7, 8]]
C = np.array(c)
print(C)
print(C.size)
print(C.shape)
print(C.ndim)

[[1 2 3 4]
 [5 6 7 8]]
8
(2, 4)
2


In [5]:
# 3d array
# [[[list][list]][[list][list]]]
d = [[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]]
D = np.array(d)
print(D)
print(D.size)
print(D.shape)
print(D.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
16
(2, 2, 4)
3


### Reshaping an array

In [6]:
a = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
A = np.array(a)
print(A)
print(A.size)
print(A.shape)
print(A.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10
(2, 5)
2


In [7]:
# changing an array from (5, 2) to (2, 5)
A.shape = (2, 5)
print(A)
print(A.shape)
print(A.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
2


In [8]:
B = np.arange(16)
print(B)
print(B.size)
print(B.shape)
print(B.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
16
(16,)
1


In [9]:
B.shape = (4, 4)
print(B)
print(B.size)
print(B.shape)
print(B.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
16
(4, 4)
2


In [10]:
B.shape = (2, 4, 2)
print(B)
print(B.size)
print(B.shape)
print(B.ndim)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]
16
(2, 4, 2)
3


In [11]:
B.shape = (2, 2, 2, 2)
print(B)
print(B.size)
print(B.shape)
print(B.ndim)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
16
(2, 2, 2, 2)
4


In [12]:
# # If you wish to convert this to 5d array, it will give a type error.
# B.shape(1, 2, 2, 2, 2)
# print(B)

### Some more play with shapes

In [13]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
a.reshape(6, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [15]:
a.reshape(6, 2, 2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]]])

In [16]:
a.reshape(2, 3, 2, 2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [18]:
B = a.reshape(2, 3, 2, 2)

In [19]:
print(B)
print(B.size)
print(B.shape)
print(B.ndim)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]
24
(2, 3, 2, 2)
4


In [20]:
B = B.reshape(2, 3, 4)
print(B)
print(B.size)
print(B.shape)
print(B.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
24
(2, 3, 4)
3
