In [1]:
import numpy as np
arr2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [2]:
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [3]:
arr2d[0]

array([1, 2, 3, 4, 5])

In [4]:
arr2d[:, 3:]

array([[ 4,  5],
       [ 9, 10]])

In [5]:
arr2d[:, 3:] = 0

In [6]:
arr2d

array([[1, 2, 3, 0, 0],
       [6, 7, 8, 0, 0]])

In [7]:
arr2d[True]

array([[[1, 2, 3, 0, 0],
        [6, 7, 8, 0, 0]]])

In [8]:
arr2d.ndim

2

In [9]:
arr2d.shape

(2, 5)

In [10]:
arr3d = np.array([[np.arange(5), np.arange(5)], [np.arange(5), np.arange(5)]])

In [11]:
arr3d

array([[[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [12]:
arr3d.ndim

3

In [13]:
arr3d[:, :, -1]

array([[4, 4],
       [4, 4]])

In [14]:
arr3d[:, :, -1] = 10

In [15]:
arr3d

array([[[ 0,  1,  2,  3, 10],
        [ 0,  1,  2,  3, 10]],

       [[ 0,  1,  2,  3, 10],
        [ 0,  1,  2,  3, 10]]])

In [16]:
arr3d = np.array([[np.arange(5), np.arange(5)], [np.arange(5), np.arange(5)]])

In [17]:
arr3d

array([[[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [18]:
arr3d.shape

(2, 2, 5)

In [25]:
arr3d[arr3d % 2 == 0] = 0

In [26]:
arr3d

array([[[0, 1, 0, 3, 0],
        [0, 1, 0, 3, 0]],

       [[0, 1, 0, 3, 0],
        [0, 1, 0, 3, 0]]])