In [1]:
# performance numpy vs traditional loop in python
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [2]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 31.9 ms


In [3]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 744 ms


## The NumPy ndarray: A Multidimensional Array Object

In [4]:
import numpy as np
# generate some random data
data = np.random.randn(2, 3)
data

array([[ 0.21403686, -1.10081403, -1.11630171],
       [ 0.31898678, -0.76714201, -0.61565232]])

In [5]:
data * 10

array([[  2.14036859, -11.00814033, -11.16301715],
       [  3.18986777,  -7.67142011,  -6.15652321]])

In [7]:
data + data

array([[ 0.42807372, -2.20162807, -2.23260343],
       [ 0.63797355, -1.53428402, -1.23130464]])

In [9]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

### Creating ndarrays

In [13]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
data2 = [[1, 2, 3, 4,], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr2.size

8

In [16]:
arr2.shape

(2, 4)

In [17]:
arr2.ndim

2

In [18]:
ex1 = [[1, 2, 3, 4,], [5, 6, 7, 8], [9, 10, 11, 12]]
ex1_arr = np.array(ex1)
ex1_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
ex1_arr.shape

(3, 4)

In [21]:
ex1_arr.ndim  # This is still a 2 dimensional array

2

In [22]:
ex2 = [[1, 2, 3, 4,], [5, 6, 7, 8], [9, 10, 11, 12]], [2, 4, 6, 8]
ex2_arr = np.array(ex2)
ex2_arr

c:\code\venv\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


array([list([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]),
       list([2, 4, 6, 8])], dtype=object)

In [24]:
ex3 = [[1, 2, 3, 4,], [5, 6, 7, 8], [9, 10, 11, 12]], [[2, 4, 6, 8], [1, 3, 5, 7]]
ex3_arr = np.array(ex3, dtype=object)
ex3_arr

array([list([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]),
       list([[2, 4, 6, 8], [1, 3, 5, 7]])], dtype=object)

In [25]:
ex3_arr.shape

(2,)

In [26]:
ex3_arr.size

2

In [27]:
ex3_arr.ndim

1

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [36]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [50]:
x = np.zeros((2, 3, 4,))

In [51]:
x.shape

(2, 3, 4)

In [52]:
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [53]:
x.ndim

3

In [54]:
a = np.array(10)
b = np.array(10.45)
print(a)
print(b)
print(a.ndim)
print(b.ndim)

10
10.45
0
0


In [55]:
# creating 2d array
a = [[1, 2, 3,], [4, 5, 6,], [7, 8, 9,]]
a = np.array(a)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
print(a.ndim)

2


In [57]:
# Creating 3d array.
a = [[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]
a = np.array(a)
print(a)
print(a.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3


In [59]:
# more arrays
a = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
            [10, 11, 12]])
print(a)
print(a.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2


In [60]:
print(np.shape(a))

(4, 3)


In [61]:
# 3d arrays
a = np.array([[[1], [2]], [[3], [4]], [[5], [6]]])
print(a)
print(a.shape)
print(a.ndim)

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]
(3, 2, 1)
3


### Data Types for ndarrays

In [62]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [63]:
# Casting an array dtype
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [65]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

### Arthmetic with NumPy Arrays

In [66]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [67]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [68]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [69]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [70]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [71]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [72]:
arr2 = np.array([[0.,4.,1.], [7., 2., 12.]])

In [73]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [74]:
arr2 > arr1

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing ans Slicing

In [75]:
arr = np.arange(10)

In [76]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
arr[5]

5

In [78]:
arr[5:8]

array([5, 6, 7])

In [79]:
arr[5:8] = 12

In [80]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [81]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [82]:
arr_slice[1] = 12345

In [83]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [84]:
# bare slice
arr_slice[:] = 64

In [85]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [86]:
# with multidimentional arrays
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [87]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
arr2d[2]

array([7, 8, 9])

In [91]:
arr2d[2][2]

9

In [92]:
arr2d[2, 2]

9

In [93]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [94]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [95]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
arr3d[0, 1]

array([4, 5, 6])

In [97]:
arr3d[0, 1, 2]

6

### Boolean Indexing

In [98]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [99]:
data = np.random.randn(7, 4)

In [100]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [101]:
data

array([[ 0.70601892,  0.52129313, -1.07610982,  1.26276536],
       [ 1.06967449,  0.65619348, -1.05217337,  1.6915527 ],
       [-0.73443885, -0.15580356, -2.23014961, -1.1162366 ],
       [ 0.48236299, -0.31512892,  0.63073346,  0.60857401],
       [ 1.45213813, -0.97116975, -0.11886615, -0.02923537],
       [-0.07935587,  1.05268877,  0.03278469, -1.76999659],
       [ 0.46602312,  0.76723809,  0.47245198, -0.85078738]])

In [105]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [107]:
data[names == 'Bob']

array([[ 0.70601892,  0.52129313, -1.07610982,  1.26276536],
       [ 0.48236299, -0.31512892,  0.63073346,  0.60857401]])

In [108]:
data[names == 'Bob', 2:]  # sub selection

array([[-1.07610982,  1.26276536],
       [ 0.63073346,  0.60857401]])

In [109]:
mask = (names == 'Bob') | (names == 'Will')

In [110]:
mask

array([ True, False,  True,  True,  True, False, False])

In [111]:
data[mask]

array([[ 0.70601892,  0.52129313, -1.07610982,  1.26276536],
       [-0.73443885, -0.15580356, -2.23014961, -1.1162366 ],
       [ 0.48236299, -0.31512892,  0.63073346,  0.60857401],
       [ 1.45213813, -0.97116975, -0.11886615, -0.02923537]])

### Fancy Indexing

In [112]:
arr = np.empty((8, 4))

In [113]:
arr

array([[6.26968827e-312, 1.06224114e-321, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 5.02034658e+175, 4.05118311e+174,
        9.51328175e-047],
       [2.87821434e+180, 2.67787768e-032, 2.33574072e-052,
        8.07241454e-144],
       [3.59751658e+252, 1.46901661e+179, 8.37404147e+242,
        2.59027926e-144],
       [3.80985069e+180, 1.14428494e+243, 2.59027907e-144,
        7.79952704e-143],
       [1.10510902e-046, 6.57700522e-038, 6.34992453e-066,
        2.19189346e-076],
       [2.59027864e-144, 2.59903818e-144, 5.58166867e-091,
        4.67391575e-062],
       [1.31425184e-047, 1.11475752e+261, 1.16318408e-028,
        2.97707521e+296]])

In [114]:
for i in range(8):
    arr[i] = i

In [115]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [117]:
# getting a subset of data in desired order
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [118]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [121]:
arr = np.arange(32).reshape((8, 4))

In [122]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [123]:
arr[[1, 5, 7, 2],[0, 3, 1, 2]]  # equivalent to (1, 0), (5, 3) etc.

array([ 4, 23, 29, 10])

### Transposing Arrays and Swapping Axes

In [124]:
arr = np.arange(15).reshape((3, 5))

In [125]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [126]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])