In [2]:
import numpy as np
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [7]:
# unary ufuncs
x = np.random.randn(8)
y = np.random.randn(8)

In [8]:
np.maximum(x, y)

array([ 1.40480291, -0.19217814,  0.58584366,  1.33459269, -0.29769987,
        0.55122276,  0.05947824, -0.01975607])

In [9]:
# multiple returns.
arr = np.random.randn(7) * 5

In [10]:
arr

array([-4.85547045, -1.41704841, -5.20202423,  0.03843893, -5.59402049,
       -1.37653512, -0.80164293])

In [11]:
remainder, whole_part = np.modf(arr)

In [12]:
print(remainder)
print(whole_part)

[-0.85547045 -0.41704841 -0.20202423  0.03843893 -0.59402049 -0.37653512
 -0.80164293]
[-4. -1. -5.  0. -5. -1. -0.]
